var DAY_LENGTH = {
	"0": "Day length not available",
	"1": "Full day",
	"2": "Full day and Half Day",
	"3": "Half Day",
	"4": "5-Hour",
	"5": "Full Day and 5-Hour",
	"6": "Half Day and 5-hour",
	"7": "Full Day, Half Day and 5-hour"			
},
INDOOR_OUTDOOR = {
	"1": "Indoor playspace",
	"2": "Indoor/Outdoor (offsite) playspace",
	"3": "Indoor/Outdoor (onsite) playspace",
	"4": "Indoor/Outdoor (onsite) playspace/Outdoor (offsite) playspace",
	"5": "Playspace not offered",
	"6": "Outdoor (offsite) playspace",
	"7": "Outdoor (onsite) playspace",
	"8": "Outdoor (onsite) playspace/Outdoor (offsite) playspace",
	"9": "Please contact site directly for information about playspace"
},
MEALS = {
	"1": "Breakfast",
	"2": "Breakfast/Lunch",
	"3": "Breakfast/Lunch/Snack(s)",
	"4": "Breakfast/Snack(s)",
	"5": "Please contact site directly for information about meals",
	"6": "Lunch",
	"7": "Lunch/Snack(s)",
	"8": "Snack(s)"
},
BOROUGH = {"M":"Manhattan", "X":"Bronx", "K":"Brooklyn", "Q":"Queens", "R":"Staten Island"},
ENHANCED_LANG = {
	"100": "<b>Dual Language:</b> Arabic",
	"101": "<b>Dual Language:</b> Bengali",
	"102": "<b>Dual Language:</b> Chinese",
	"103": "<b>Dual Language:</b> Chinese (Mandarin)",
	"104": "<b>Dual Language:</b> Chinese (Cantonese)",
	"105": "<b>Dual Language:</b> French",
	"106": "<b>Dual Language:</b> Haitian-Creole",
	"107": "<b>Dual Language:</b> Korean",
	"108": "<b>Dual Language:</b> Russian",
	"109": "<b>Dual Language:</b> Spanish",
	"110": "<b>Dual Language:</b> Urdu",
	"111": "<b>Dual Language:</b> Hindi",
	"112": "<b>Dual Language:</b> Gujarati",
	"113": "<b>Dual Language:</b> Hebrew",
	"114": "<b>Dual Language:</b> Polish",
	"115": "<b>Dual Language:</b> Japanese",
	"116": "<b>Dual Language:</b> Italian",
	"117": "<b>Dual Language:</b> Yiddish",
	"118": "<b>Dual Language:</b> Portuguese",
	"119": "<b>Dual Language:</b> Tagalog",
	"120": "<b>Dual Language:</b> Greek",
	"121": "<b>Dual Language:</b> German",
	"122": "<b>Dual Language:</b> Farsi",
	"123": "<b>Dual Language:</b> Vietnamese",
	"200": "<b>Enhanced Language Support:</b>  Arabic",
	"201": "<b>Enhanced Language Support:</b>  Bengali",
	"202": "<b>Enhanced Language Support:</b>  Chinese",
	"203": "<b>Enhanced Language Support:</b>  Chinese (Mandarin)",
	"204": "<b>Enhanced Language Support:</b>  Chinese (Cantonese)",
	"205": "<b>Enhanced Language Support:</b>  French",
	"206": "<b>Enhanced Language Support:</b>  Haitian-Creole",
	"207": "<b>Enhanced Language Support:</b>  Korean",
	"208": "<b>Enhanced Language Support:</b>  Russian",
	"209": "<b>Enhanced Language Support:</b>  Spanish",
	"210": "<b>Enhanced Language Support:</b>  Urdu",
	"211": "<b>Enhanced Language Support:</b>  Hindi",
	"212": "<b>Enhanced Language Support:</b>  Gujarati",
	"213": "<b>Enhanced Language Support:</b>  Hebrew",
	"214": "<b>Enhanced Language Support:</b>  Polish",
	"215": "<b>Enhanced Language Support:</b>  Japanese",
	"216": "<b>Enhanced Language Support:</b>  Italian",
	"217": "<b>Enhanced Language Support:</b>  Yiddish",
	"218": "<b>Enhanced Language Support:</b>  Portuguese",
	"219": "<b>Enhanced Language Support:</b>  Tagalog",
	"220": "<b>Enhanced Language Support:</b>  Greek",
	"221": "<b>Enhanced Language Support:</b>  German",
	"222": "<b>Enhanced Language Support:</b>  Farsi",
	"223": "<b>Enhanced Language Support:</b>  Vietnamese"
},
FLEX_SCHED = "<b>Alert:</b> Program may utilize flexible scheduling policy. Please contact program directly for details about pre-K schedule.",
SPED_FLG = "<b>Alert:</b> If your child has an IEP recommending Related Services and/or SEIT, contact the program directly for more information before applying.",
INCOME_ELG = "<b>Alert:</b> Program may have income or other eligibility requirements. Contact for more information.";

