var DAY_LENGTH = {
	"0": "Day length not available",
	"1": "Full day",
	"2": "Full day and Half Day",
	"3": "Half Day",
	"4": "5-Hour",
	"5": "Full Day and 5-Hour",
	"6": "Half Day and 5-hour",
	"7": "Full Day, Half Day and 5-hour"			
},
INDOOR_OUTDOOR = {
	"1": "Indoor playspace",
	"2": "Indoor/Outdoor (offsite) playspace",
	"3": "Indoor/Outdoor (onsite) playspace",
	"4": "Indoor/Outdoor (onsite) playspace/Outdoor (offsite) playspace",
	"5": "Playspace not offered",
	"6": "Outdoor (offsite) playspace",
	"7": "Outdoor (onsite) playspace",
	"8": "Outdoor (onsite) playspace/Outdoor (offsite) playspace",
	"9": "Please contact site directly for information about playspace"
},
MEALS = {
	"1": "Breakfast",
	"2": "Breakfast/Lunch",
	"3": "Breakfast/Lunch/Snack(s)",
	"4": "Breakfast/Snack(s)",
	"5": "Please contact site directly for information about meals",
	"6": "Lunch",
	"7": "Lunch/Snack(s)",
	"8": "Snack(s)"
},
BOROUGH = {"M":"Manhattan", "X":"Bronx", "K":"Brooklyn", "Q":"Queens", "R":"Staten Island"},
DUAL_LANG = {
	"100": "Arabic",
	"101": "Bengali",
	"102": "Chinese",
	"103": "Chinese (Mandarin)",
	"104": "Chinese (Cantonese)",
	"105": "French",
	"106": "Haitian-Creole",
	"107": "Korean",
	"108": "Russian",
	"109": "Spanish",
	"110": "Urdu",
	"111": "Hindi",
	"112": "Gujarati",
	"113": "Hebrew",
	"114": "Polish",
	"115": "Japanese",
	"116": "Italian",
	"117": "Yiddish",
	"118": "Portuguese",
	"119": "Tagalog",
	"120": "Greek",
	"121": "German",
	"122": "Farsi",
	"123": "Vietnamese"
},
ENHANCED_LANG = {
	"200": "Arabic",
	"201": "Bengali",
	"202": "Chinese",
	"203": "Chinese (Mandarin)",
	"204": "Chinese (Cantonese)",
	"205": "French",
	"206": "Haitian-Creole",
	"207": "Korean",
	"208": "Russian",
	"209": "Spanish",
	"210": "Urdu",
	"211": "Hindi",
	"212": "Gujarati",
	"213": "Hebrew",
	"214": "Polish",
	"215": "Japanese",
	"216": "Italian",
	"217": "Yiddish",
	"218": "Portuguese",
	"219": "Tagalog",
	"220": "Greek",
	"221": "German",
	"222": "Farsi",
	"223": "Vietnamese"
},
FLEX_SCHED = "<b>Alert:</b> Program may utilize flexible scheduling policy. Please contact program directly for details about pre-K schedule.",
SPED_FLG = "<b>Alert:</b> If your child has an IEP recommending Related Services and/or SEIT, contact the program directly for more information before applying.",
INCOME_FLG = "<b>Alert:</b> Program may have income or other eligibility requirements. Contact for more information.";

